# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guilhermeaj/Compilador

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guilhermeaj/Compilador

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guilhermeaj/Compilador/CMakeFiles /home/guilhermeaj/Compilador//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guilhermeaj/Compilador/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/binary_tree/binary_tree.o: src/binary_tree/binary_tree.cpp.o
.PHONY : src/binary_tree/binary_tree.o

# target to build an object file
src/binary_tree/binary_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/binary_tree/binary_tree.cpp.o
.PHONY : src/binary_tree/binary_tree.cpp.o

src/binary_tree/binary_tree.i: src/binary_tree/binary_tree.cpp.i
.PHONY : src/binary_tree/binary_tree.i

# target to preprocess a source file
src/binary_tree/binary_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/binary_tree/binary_tree.cpp.i
.PHONY : src/binary_tree/binary_tree.cpp.i

src/binary_tree/binary_tree.s: src/binary_tree/binary_tree.cpp.s
.PHONY : src/binary_tree/binary_tree.s

# target to generate assembly for a file
src/binary_tree/binary_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/binary_tree/binary_tree.cpp.s
.PHONY : src/binary_tree/binary_tree.cpp.s

src/compiler/compiler.o: src/compiler/compiler.cpp.o
.PHONY : src/compiler/compiler.o

# target to build an object file
src/compiler/compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/compiler/compiler.cpp.o
.PHONY : src/compiler/compiler.cpp.o

src/compiler/compiler.i: src/compiler/compiler.cpp.i
.PHONY : src/compiler/compiler.i

# target to preprocess a source file
src/compiler/compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/compiler/compiler.cpp.i
.PHONY : src/compiler/compiler.cpp.i

src/compiler/compiler.s: src/compiler/compiler.cpp.s
.PHONY : src/compiler/compiler.s

# target to generate assembly for a file
src/compiler/compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/compiler/compiler.cpp.s
.PHONY : src/compiler/compiler.cpp.s

src/lexical_analyser/lexical_analyser.o: src/lexical_analyser/lexical_analyser.cpp.o
.PHONY : src/lexical_analyser/lexical_analyser.o

# target to build an object file
src/lexical_analyser/lexical_analyser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/lexical_analyser.cpp.o
.PHONY : src/lexical_analyser/lexical_analyser.cpp.o

src/lexical_analyser/lexical_analyser.i: src/lexical_analyser/lexical_analyser.cpp.i
.PHONY : src/lexical_analyser/lexical_analyser.i

# target to preprocess a source file
src/lexical_analyser/lexical_analyser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/lexical_analyser.cpp.i
.PHONY : src/lexical_analyser/lexical_analyser.cpp.i

src/lexical_analyser/lexical_analyser.s: src/lexical_analyser/lexical_analyser.cpp.s
.PHONY : src/lexical_analyser/lexical_analyser.s

# target to generate assembly for a file
src/lexical_analyser/lexical_analyser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/lexical_analyser.cpp.s
.PHONY : src/lexical_analyser/lexical_analyser.cpp.s

src/lexical_analyser/token.o: src/lexical_analyser/token.cpp.o
.PHONY : src/lexical_analyser/token.o

# target to build an object file
src/lexical_analyser/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token.cpp.o
.PHONY : src/lexical_analyser/token.cpp.o

src/lexical_analyser/token.i: src/lexical_analyser/token.cpp.i
.PHONY : src/lexical_analyser/token.i

# target to preprocess a source file
src/lexical_analyser/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token.cpp.i
.PHONY : src/lexical_analyser/token.cpp.i

src/lexical_analyser/token.s: src/lexical_analyser/token.cpp.s
.PHONY : src/lexical_analyser/token.s

# target to generate assembly for a file
src/lexical_analyser/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token.cpp.s
.PHONY : src/lexical_analyser/token.cpp.s

src/lexical_analyser/token_property.o: src/lexical_analyser/token_property.cpp.o
.PHONY : src/lexical_analyser/token_property.o

# target to build an object file
src/lexical_analyser/token_property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token_property.cpp.o
.PHONY : src/lexical_analyser/token_property.cpp.o

src/lexical_analyser/token_property.i: src/lexical_analyser/token_property.cpp.i
.PHONY : src/lexical_analyser/token_property.i

# target to preprocess a source file
src/lexical_analyser/token_property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token_property.cpp.i
.PHONY : src/lexical_analyser/token_property.cpp.i

src/lexical_analyser/token_property.s: src/lexical_analyser/token_property.cpp.s
.PHONY : src/lexical_analyser/token_property.s

# target to generate assembly for a file
src/lexical_analyser/token_property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token_property.cpp.s
.PHONY : src/lexical_analyser/token_property.cpp.s

src/lexical_analyser/token_type.o: src/lexical_analyser/token_type.cpp.o
.PHONY : src/lexical_analyser/token_type.o

# target to build an object file
src/lexical_analyser/token_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token_type.cpp.o
.PHONY : src/lexical_analyser/token_type.cpp.o

src/lexical_analyser/token_type.i: src/lexical_analyser/token_type.cpp.i
.PHONY : src/lexical_analyser/token_type.i

# target to preprocess a source file
src/lexical_analyser/token_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token_type.cpp.i
.PHONY : src/lexical_analyser/token_type.cpp.i

src/lexical_analyser/token_type.s: src/lexical_analyser/token_type.cpp.s
.PHONY : src/lexical_analyser/token_type.s

# target to generate assembly for a file
src/lexical_analyser/token_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/lexical_analyser/token_type.cpp.s
.PHONY : src/lexical_analyser/token_type.cpp.s

src/log/log.o: src/log/log.cpp.o
.PHONY : src/log/log.o

# target to build an object file
src/log/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/log/log.cpp.o
.PHONY : src/log/log.cpp.o

src/log/log.i: src/log/log.cpp.i
.PHONY : src/log/log.i

# target to preprocess a source file
src/log/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/log/log.cpp.i
.PHONY : src/log/log.cpp.i

src/log/log.s: src/log/log.cpp.s
.PHONY : src/log/log.s

# target to generate assembly for a file
src/log/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/log/log.cpp.s
.PHONY : src/log/log.cpp.s

src/log/log_thread_safe.o: src/log/log_thread_safe.cpp.o
.PHONY : src/log/log_thread_safe.o

# target to build an object file
src/log/log_thread_safe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/log/log_thread_safe.cpp.o
.PHONY : src/log/log_thread_safe.cpp.o

src/log/log_thread_safe.i: src/log/log_thread_safe.cpp.i
.PHONY : src/log/log_thread_safe.i

# target to preprocess a source file
src/log/log_thread_safe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/log/log_thread_safe.cpp.i
.PHONY : src/log/log_thread_safe.cpp.i

src/log/log_thread_safe.s: src/log/log_thread_safe.cpp.s
.PHONY : src/log/log_thread_safe.s

# target to generate assembly for a file
src/log/log_thread_safe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/log/log_thread_safe.cpp.s
.PHONY : src/log/log_thread_safe.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/semantic_analyser/scope.o: src/semantic_analyser/scope.cpp.o
.PHONY : src/semantic_analyser/scope.o

# target to build an object file
src/semantic_analyser/scope.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semantic_analyser/scope.cpp.o
.PHONY : src/semantic_analyser/scope.cpp.o

src/semantic_analyser/scope.i: src/semantic_analyser/scope.cpp.i
.PHONY : src/semantic_analyser/scope.i

# target to preprocess a source file
src/semantic_analyser/scope.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semantic_analyser/scope.cpp.i
.PHONY : src/semantic_analyser/scope.cpp.i

src/semantic_analyser/scope.s: src/semantic_analyser/scope.cpp.s
.PHONY : src/semantic_analyser/scope.s

# target to generate assembly for a file
src/semantic_analyser/scope.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semantic_analyser/scope.cpp.s
.PHONY : src/semantic_analyser/scope.cpp.s

src/semantic_analyser/semantic_analyser.o: src/semantic_analyser/semantic_analyser.cpp.o
.PHONY : src/semantic_analyser/semantic_analyser.o

# target to build an object file
src/semantic_analyser/semantic_analyser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semantic_analyser/semantic_analyser.cpp.o
.PHONY : src/semantic_analyser/semantic_analyser.cpp.o

src/semantic_analyser/semantic_analyser.i: src/semantic_analyser/semantic_analyser.cpp.i
.PHONY : src/semantic_analyser/semantic_analyser.i

# target to preprocess a source file
src/semantic_analyser/semantic_analyser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semantic_analyser/semantic_analyser.cpp.i
.PHONY : src/semantic_analyser/semantic_analyser.cpp.i

src/semantic_analyser/semantic_analyser.s: src/semantic_analyser/semantic_analyser.cpp.s
.PHONY : src/semantic_analyser/semantic_analyser.s

# target to generate assembly for a file
src/semantic_analyser/semantic_analyser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semantic_analyser/semantic_analyser.cpp.s
.PHONY : src/semantic_analyser/semantic_analyser.cpp.s

src/syntactic_analyser/non_terminal.o: src/syntactic_analyser/non_terminal.cpp.o
.PHONY : src/syntactic_analyser/non_terminal.o

# target to build an object file
src/syntactic_analyser/non_terminal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/non_terminal.cpp.o
.PHONY : src/syntactic_analyser/non_terminal.cpp.o

src/syntactic_analyser/non_terminal.i: src/syntactic_analyser/non_terminal.cpp.i
.PHONY : src/syntactic_analyser/non_terminal.i

# target to preprocess a source file
src/syntactic_analyser/non_terminal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/non_terminal.cpp.i
.PHONY : src/syntactic_analyser/non_terminal.cpp.i

src/syntactic_analyser/non_terminal.s: src/syntactic_analyser/non_terminal.cpp.s
.PHONY : src/syntactic_analyser/non_terminal.s

# target to generate assembly for a file
src/syntactic_analyser/non_terminal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/non_terminal.cpp.s
.PHONY : src/syntactic_analyser/non_terminal.cpp.s

src/syntactic_analyser/syntactic_analyser.o: src/syntactic_analyser/syntactic_analyser.cpp.o
.PHONY : src/syntactic_analyser/syntactic_analyser.o

# target to build an object file
src/syntactic_analyser/syntactic_analyser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/syntactic_analyser.cpp.o
.PHONY : src/syntactic_analyser/syntactic_analyser.cpp.o

src/syntactic_analyser/syntactic_analyser.i: src/syntactic_analyser/syntactic_analyser.cpp.i
.PHONY : src/syntactic_analyser/syntactic_analyser.i

# target to preprocess a source file
src/syntactic_analyser/syntactic_analyser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/syntactic_analyser.cpp.i
.PHONY : src/syntactic_analyser/syntactic_analyser.cpp.i

src/syntactic_analyser/syntactic_analyser.s: src/syntactic_analyser/syntactic_analyser.cpp.s
.PHONY : src/syntactic_analyser/syntactic_analyser.s

# target to generate assembly for a file
src/syntactic_analyser/syntactic_analyser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/syntactic_analyser.cpp.s
.PHONY : src/syntactic_analyser/syntactic_analyser.cpp.s

src/syntactic_analyser/term.o: src/syntactic_analyser/term.cpp.o
.PHONY : src/syntactic_analyser/term.o

# target to build an object file
src/syntactic_analyser/term.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/term.cpp.o
.PHONY : src/syntactic_analyser/term.cpp.o

src/syntactic_analyser/term.i: src/syntactic_analyser/term.cpp.i
.PHONY : src/syntactic_analyser/term.i

# target to preprocess a source file
src/syntactic_analyser/term.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/term.cpp.i
.PHONY : src/syntactic_analyser/term.cpp.i

src/syntactic_analyser/term.s: src/syntactic_analyser/term.cpp.s
.PHONY : src/syntactic_analyser/term.s

# target to generate assembly for a file
src/syntactic_analyser/term.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/syntactic_analyser/term.cpp.s
.PHONY : src/syntactic_analyser/term.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/binary_tree/binary_tree.o"
	@echo "... src/binary_tree/binary_tree.i"
	@echo "... src/binary_tree/binary_tree.s"
	@echo "... src/compiler/compiler.o"
	@echo "... src/compiler/compiler.i"
	@echo "... src/compiler/compiler.s"
	@echo "... src/lexical_analyser/lexical_analyser.o"
	@echo "... src/lexical_analyser/lexical_analyser.i"
	@echo "... src/lexical_analyser/lexical_analyser.s"
	@echo "... src/lexical_analyser/token.o"
	@echo "... src/lexical_analyser/token.i"
	@echo "... src/lexical_analyser/token.s"
	@echo "... src/lexical_analyser/token_property.o"
	@echo "... src/lexical_analyser/token_property.i"
	@echo "... src/lexical_analyser/token_property.s"
	@echo "... src/lexical_analyser/token_type.o"
	@echo "... src/lexical_analyser/token_type.i"
	@echo "... src/lexical_analyser/token_type.s"
	@echo "... src/log/log.o"
	@echo "... src/log/log.i"
	@echo "... src/log/log.s"
	@echo "... src/log/log_thread_safe.o"
	@echo "... src/log/log_thread_safe.i"
	@echo "... src/log/log_thread_safe.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/semantic_analyser/scope.o"
	@echo "... src/semantic_analyser/scope.i"
	@echo "... src/semantic_analyser/scope.s"
	@echo "... src/semantic_analyser/semantic_analyser.o"
	@echo "... src/semantic_analyser/semantic_analyser.i"
	@echo "... src/semantic_analyser/semantic_analyser.s"
	@echo "... src/syntactic_analyser/non_terminal.o"
	@echo "... src/syntactic_analyser/non_terminal.i"
	@echo "... src/syntactic_analyser/non_terminal.s"
	@echo "... src/syntactic_analyser/syntactic_analyser.o"
	@echo "... src/syntactic_analyser/syntactic_analyser.i"
	@echo "... src/syntactic_analyser/syntactic_analyser.s"
	@echo "... src/syntactic_analyser/term.o"
	@echo "... src/syntactic_analyser/term.i"
	@echo "... src/syntactic_analyser/term.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

